### Get languages

GET http://localhost:2000/api HTTP/1.1

### Java compile error

POST http://localhost:2000/api/java-15.0.2 HTTP/1.1
content-type: application/json

{
  "sourceRefs": ["gs://codee-club-emu.appspot.com/examples/Example1CompileError.java"],
  "inputs": {
    "1": "hello THERE",
    "2": "aBcDeF"
  }
}

### Java no main

POST http://localhost:2000/api/java-15.0.2 HTTP/1.1
content-type: application/json

{
  "sourceRefs": ["gs://codee-club-emu.appspot.com/examples/Example1NoMain.java"],
  "inputs": {
    "1": "hello THERE",
    "2": "aBcDeF"
  }
}

### Java runtime exception

POST http://localhost:2000/api/java-15.0.2 HTTP/1.1
content-type: application/json

{
  "sourceRefs": ["gs://codee-club-emu.appspot.com/examples/Example1RuntimeException.java"],
  "inputs": {
    "1": "hello THERE",
    "2": "aBcDeF"
  }
}

### Java stack overflow

POST http://localhost:2000/api/java-15.0.2 HTTP/1.1
content-type: application/json

{
  "sourceRefs": ["gs://codee-club-emu.appspot.com/examples/Example1StackOverflow.java"],
  "inputs": {
    "1": "hello THERE",
    "2": "aBcDeF"
  }
}

### Java waiting for input (timeout)

POST http://localhost:2000/api/java-15.0.2 HTTP/1.1
content-type: application/json

{
  "sourceRefs": ["gs://codee-club-emu.appspot.com/examples/Example1WaitInput.java"],
  "inputs": {
    "1": "hello THERE",
    "2": "aBcDeF"
  }
}

### Java infinite loop (timeout)

POST http://localhost:2000/api/java-15.0.2 HTTP/1.1
content-type: application/json

{
  "sourceRefs": ["gs://codee-club-emu.appspot.com/examples/Example1InfiniteLoop.java"],
  "inputs": {
    "1": "hello THERE",
    "2": "aBcDeF"
  }
}

### Java fail test

POST http://localhost:2000/api/java-15.0.2 HTTP/1.1
content-type: application/json

{
  "sourceRefs": ["gs://codee-club-emu.appspot.com/examples/Example1Fail.java"],
  "inputs": {
    "1": "hello THERE",
    "2": "aBcDeF"
  }
}

### Java pass test

POST http://localhost:2000/api/java-15.0.2 HTTP/1.1
content-type: application/json

{
  "sourceRefs": ["gs://codee-club-emu.appspot.com/examples/Example1Success.java"],
  "inputs": {
    "1": "hello THERE",
    "2": "aBcDeF"
  }
}
